export declare enum ErrorActionType {
    TIMEOUT = "TIMEOUT",
    INVALID_PAYLOAD = "INVALID_PAYLOAD",
    NETWORK = "NETWORK",
    PERMISSION = "PERMISSION",
    FAILED_AUTHENTICATION = "FAILED_AUTHENTICATION",
    INVALID_ACTION = "INVALID_ACTION",
    INVALID_ACTION_TYPE = "INVALID_ACTION_TYPE",
    MISSING_ACTION_TYPE = "MISSING_ACTION_TYPE",
    INVALID_NAVIGATION_TYPE = "INVALID_NAVIGATION_TYPE",
    INVALID_MESSAGE_TYPE = "INVALID_MESSAGE_TYPE",
    MISSING_MESSAGE_TYPE = "MISSING_MESSAGE_TYPE",
    INVALID_OPTIONS = "INVALID_OPTIONS",
    UNEXPECTED_ACTION = "UNEXPECTED_ACTION",
    UNSUPPORTED_OPERATION = "UNSUPPORTED_OPERATION",
    INVALID_ORIGIN = "INVALID_ORIGIN",
    INVALID_CONFIG = "INVALID_CONFIG",
    MISSING_CONFIG = "MISSING_CONFIG",
    IFRAME_UNDEFINED = "IFRAME_UNDEFINED",
    MISSING_LOCAL_ORIGIN = "MISSING_LOCAL_ORIGIN",
    MISSING_HOST_PROVIDER = "MISSING_HOST_PROVIDER",
    MISSING_ROUTER_CONTEXT = "MISSING_ROUTER_CONTEXT",
    MISSING_HISTORY_BLOCK = "MISSING_HISTORY_BLOCK",
    UNKNOWN = "UNKNOWN",
    HEARTBEAT_STOPPED = "HEARTBEAT_STOPPED",
    HEARTBEAT_TIMEOUT = "HEARTBEAT_TIMEOUT"
}
export declare class ErrorAction {
    type: ErrorActionType;
    payload?: Object;
    constructor(init: {
        type: ErrorActionType;
        payload?: object;
    });
}
